on: push
name: Build and release on push
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 10.x
        uses: actions/setup-node@v1
        with:
          node-version: 10.x
      - name: install dependencies
        run: yarn
      - name: Build
        run: yarn build
      - name: Release
        uses: fnkr/github-action-ghr@v1
        env:
          GHR_COMPRESS: tar.gz
          GHR_PATH: dist/
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
